easy_admin:
    entities:
        # List the entity class name you want to manage
        Utilisateur:
            class: App\Entity\Utilisateur
            form:
                fields:
                    - nom
                    - prenom
                    - email
                    - categorie
                    - message
                    - newsLetter
                    - pays
            list:
                fields: [nom, prenom, email, categorie, message, newsLetter, pays]
        Actualitees:
            class: App\Entity\Actualitees
            form:
                fields:
                    - lien
                    - titre
                    - { property: 'imageFile', type: 'file' }
                    - { property: 'contenu', type: 'fos_ckeditor' }
            list:
                fields:
                    - lien
                    - titre
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
                    - contenu
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
    design:
        menu:
            - Utilisateur
            - Actualitees
            - { label: 'NewsLetter', route: 'news_letter' }
    site_name: The View