easy_admin:
    entities:
        # List the entity class name you want to manage
        Utilisateur:
            class: App\Entity\Utilisateur
            form:
                fields:
                    - nom
                    - prenom
                    - email
                    - categorie
                    - message
                    - newsLetter
                    - pays
            list:
                fields: [nom, prenom, email, categorie, message, newsLetter, pays]
        Actualitees:
            class: App\Entity\Actualitees
            form:
                fields:
                    - lien
                    - titre
                    - image
                    - contenu
                list:
                    fields: [lien, titre, image, contenu]
    site_name: the view